const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={page:'home',rates:{usd:null,eur:null,aed:null,try:null,xau:null,btc:null},updated:null};
const nav=[['home','خانه','i-home'],['markets','بازار','i-market'],['trade','معامله','i-trade'],['wallet','دارایی','i-wallet'],['more','بیشتر','i-grid']];
const icon=k=>`<span class="i ${k}"></span>`;
function navHtml(){return nav.map(([p,t,i])=>`<button data-page="${p}" class="${state.page===p?'active':''} ${p==='trade'?'center':''}">${icon(i)}<b>${t}</b></button>`).join('')}
function railHtml(){return nav.map(([p,t,i])=>`<button data-page="${p}" class="${state.page===p?'active':''}">${icon(i)}<b>${t}</b></button>`).join('')}
function fmt(n,dec=0){if(n==null||Number.isNaN(Number(n)))return '—';return Number(n).toLocaleString('fa-IR',{maximumFractionDigits:dec})}
function usd(n){if(n==null)return '—';return Number(n).toLocaleString('en-US',{maximumFractionDigits:2})}
function money(n){if(n==null)return 'در انتظار داده';return fmt(n)+' ریال'}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.classList.remove('show'),2200)}
window.toast=toast;
function chart(color1='#0b5cff',color2='#0bc8d7'){const a=[35,39,34,43,41,50,47,55,51,60,58,68,63,74,70,78,73,84,81,88,85,94];const pts=a.map((v,i)=>`${(i*100/(a.length-1)).toFixed(2)},${100-v}`).join(' ');return `<svg viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="${color1}"/><stop offset="1" stop-color="${color2}"/></linearGradient><linearGradient id="a" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${color1}" stop-opacity=".16"/><stop offset="1" stop-color="${color1}" stop-opacity="0"/></linearGradient></defs><path class="grid" d="M0 20H100M0 45H100M0 70H100"/><path class="area" d="M0 100L${pts}L100 100Z"/><path class="line" d="M${pts}"/></svg>`}
function home(){const r=state.rates;return `<div class="view-head"><div><h1>نبض بازار</h1><p>نمایش زنده بازار در یک نگاه</p></div><div class="head-tools"><button class="tool-btn" onclick="refreshRates()">↻ بروزرسانی</button><button class="tool-btn primary" onclick="go('markets')">باز کردن بازار</button></div></div>
<section class="hero2"><div class="hero-copy"><span class="micro">TEEXAA / LIVE MARKET</span><h2>بازار را ببین،<br>قبل از تصمیم حرکتش را بفهم.</h2><p>TeeXaa یک نمای بازار مینیمال و متمرکز است؛ نرخ‌ها از سرویس‌های عمومی دریافت می‌شوند و زمان آخرین بروزرسانی روی صفحه نمایش داده می‌شود.</p><div class="hero-pills"><span>نرخ ارز</span><span>طلا و فلزات</span><span>رمزارز</span><span>رصد لحظه‌ای</span></div></div><div class="hero-market"><div class="pulse-card"><div class="pulse-head"><small>طلا · XAU / USD</small><span class="live">LIVE</span></div><div class="pulse-price">$${usd(r.xau)}</div><div class="pulse-change">مرجع جهانی اونس طلا</div><div class="pulse-chart">${chart('#0bc8d7','#7658ff')}</div></div></div></section>
<div class="stats"><div class="stat"><div class="stat-top"><span>دلار آمریکا</span><span>USD</span></div><strong>${r.usd?fmt(r.usd):'—'}</strong><small>ریال · مرجع</small></div><div class="stat"><div class="stat-top"><span>یورو</span><span>EUR</span></div><strong>${r.eur?fmt(r.eur):'—'}</strong><small>ریال · مرجع</small></div><div class="stat"><div class="stat-top"><span>اونس طلا</span><span>XAU</span></div><strong>$${usd(r.xau)}</strong><small>دلار آمریکا</small></div><div class="stat"><div class="stat-top"><span>بیت‌کوین</span><span>BTC</span></div><strong>$${usd(r.btc)}</strong><small>قیمت جهانی</small></div></div>
<div class="section-row"><h3>بازارهای منتخب</h3><span>${state.updated?'آخرین بروزرسانی: '+state.updated:'در حال دریافت داده...'}</span></div><div class="market-strip">${marketCard('XAU','طلا','اونس جهانی','$'+usd(r.xau),'goldbg','مرجع جهانی')}${marketCard('USD','دلار','USD / IRR',r.usd?fmt(r.usd):'—','fxbg','نرخ مرجع')}${marketCard('BTC','بیت‌کوین','BTC / USD','$'+usd(r.btc),'crypto','بازار جهانی')}${marketCard('XAG','نقره','XAG / USD','—','silverbg','درگاه بعدی')}</div>
<div class="two"><div class="card"><div class="section-row" style="margin:0"><div><h3>نمودار بازار</h3><span>نمای نمایشی روند</span></div><div class="chart-tabs"><button class="active">۱ روز</button><button>۱ هفته</button><button>۱ ماه</button></div></div><div class="chart">${chart()}</div></div><div class="card"><h3>رصد سریع</h3><div class="watch">${watch('XAU','طلا', '$'+usd(r.xau),'goldbg')}${watch('USD','دلار',r.usd?fmt(r.usd):'—','fxbg')}${watch('BTC','بیت‌کوین','$'+usd(r.btc),'crypto')}${watch('EUR','یورو',r.eur?fmt(r.eur):'—','silverbg')}</div></div></div>
<div class="section-row"><h3>دسترسی سریع</h3><span>اختصاصی TeeXaa</span></div><div class="quick">${quick('i-market','بازارها','لیست کامل نرخ‌ها','markets')}${quick('i-trade','معامله','محیط سفارش‌گذاری','trade')}${quick('i-wallet','دارایی','مدیریت دارایی‌ها','wallet')}${quick('i-bell','اعلان‌ها','رویدادهای مهم بازار','notifications')}</div></div>`}
function marketCard(sym,name,sub,price,cl,foot){return `<div class="market-card"><div class="mc-top"><span class="asset-icon ${cl}">${sym}</span><div><div class="mc-name">${name}</div><div class="mc-sub">${sub}</div></div></div><div class="mc-price">${price}</div><div class="mc-foot"><span>${foot}</span><span>●</span></div></div>`}
function watch(sym,name,price,cl){return `<div class="watch-item"><div class="left"><span class="asset-icon ${cl}">${sym}</span><div><b>${name}</b><small>${sym}</small></div></div><span class="price">${price}</span></div>`}
function quick(ic,t,s,p){return `<button class="quick-card" onclick="go('${p}')"><span class="qicon">${icon(ic)}</span><b>${t}</b><small>${s}</small></button>`}
function markets(){const r=state.rates;const rows=[['دلار آمریکا','USD / IRR',r.usd,'fxbg'],['یورو','EUR / IRR',r.eur,'silverbg'],['درهم امارات','AED / IRR',r.aed,'fxbg'],['لیر ترکیه','TRY / IRR',r.try,'silverbg'],['اونس طلا','XAU / USD',r.xau,'goldbg'],['بیت‌کوین','BTC / USD',r.btc,'crypto']];return `<div class="view-head"><div><h1>بازار</h1><p>داده‌های عمومی و زنده، با زمان آخرین بروزرسانی</p></div><div class="head-tools"><input class="search" placeholder="جست‌وجوی دارایی..." oninput="filterRows(this.value)"><button class="tool-btn primary" onclick="refreshRates()">↻</button></div></div><div class="market-layout"><div class="market-board" id="marketBoard"><div class="board-head"><span>دارایی</span><span>قیمت</span><span>واحد</span><span>وضعیت</span></div>${rows.map(x=>`<div class="market-row"><div class="asset"><span class="asset-icon ${x[3]}">${x[0].slice(0,2)}</span><div><b>${x[0]}</b><small>${x[1]}</small></div></div><div class="ltr">${x[2]==null?'—':(x[1].includes('USD')?'$'+usd(x[2]):fmt(x[2]))}</div><div>${x[1].includes('USD')?'دلار':'ریال'}</div><div class="change up">● زنده</div></div>`).join('')}</div><aside class="side-card"><span class="micro">TEEXAA DATA</span><h3 style="margin-top:14px">اتصال نرخ‌ها</h3><p>دلار، یورو، درهم و لیر از نرخ مرجع Open ER-API دریافت می‌شوند. اونس طلا و برخی دارایی‌های جهانی از Gold API دریافت می‌شوند. برای نرخ بازار آزاد ایران، اتصال مستقیم به منبعی مثل TGJU نیاز به بک‌اند/پراکسی اختصاصی دارد.</p><div class="source-line"><span>آخرین بروزرسانی</span><b>${state.updated||'—'}</b></div><button class="tool-btn" style="margin-top:14px;width:100%;background:#fff" onclick="refreshRates()">دریافت مجدد</button></aside></div>`}
function filterRows(q){const n=q.trim();$$('.market-row').forEach(x=>x.style.display=!n||x.textContent.includes(n)?'grid':'none')}
function trade(){return `<div class="view-head"><div><h1>معامله</h1><p>محیط سفارش‌گذاری نمایشی TeeXaa</p></div></div><div class="two"><div class="card"><div class="section-row" style="margin-top:0"><h3>سفارش جدید</h3><span>DEMO</span></div><div style="display:grid;gap:12px;margin-top:15px"><label style="font-size:9px;color:var(--muted)">دارایی<input class="search" style="width:100%;margin-top:6px" value="BTC / USD" readonly></label><label style="font-size:9px;color:var(--muted)">قیمت<input class="search" style="width:100%;margin-top:6px" value="${state.rates.btc?'$'+usd(state.rates.btc):'در انتظار'}" readonly></label><label style="font-size:9px;color:var(--muted)">مقدار<input id="qty" class="search" style="width:100%;margin-top:6px" placeholder="0.00"></label><button class="tool-btn primary" style="height:46px" onclick="toast('سفارش نمایشی ثبت شد')">ثبت سفارش</button></div></div><div class="card"><h3>نمای بازار</h3><p class="card-sub">نرخ فعلی بیت‌کوین</p><div style="font:700 27px 'Space Grotesk';direction:ltr;margin-top:16px">$${usd(state.rates.btc)}</div><div class="chart">${chart('#7658ff','#ee4aa8')}</div></div></div>`}
function wallet(){return `<div class="view-head"><div><h1>دارایی</h1><p>نمای شخصی دارایی‌ها در TeeXaa</p></div></div><div class="hero2" style="min-height:220px"><div class="hero-copy"><span class="micro">PORTFOLIO</span><h2 style="font-size:30px">نمای کلی دارایی</h2><p>این بخش برای نسخه متصل به حساب کاربری آماده است. موجودی واقعی تا زمان اتصال به بک‌اند نمایش داده نمی‌شود.</p><div class="hero-pills"><span>امنیت</span><span>تبدیل</span><span>واریز</span><span>برداشت</span></div></div><div class="hero-market"><div class="pulse-card"><div class="pulse-head"><small>ارزش نمونه</small><span class="live">LOCAL</span></div><div class="pulse-price">$0.00</div><div class="pulse-change">هنوز حسابی متصل نشده</div></div></div></div><div class="section-row"><h3>ابزارها</h3></div><div class="quick">${quick('i-wallet','واریز','اتصال به درگاه','wallet')}${quick('i-trade','تبدیل','تبدیل دارایی','trade')}${quick('i-market','بازار','مشاهده قیمت','markets')}${quick('i-lock','امنیت','کنترل دسترسی','security')}</div>`}
function more(){const items=[['i-grid','تنظیمات','ظاهر و تجربه TeeXaa'],['i-bell','اعلان‌ها','رویدادهای مهم بازار'],['i-lock','امنیت','امنیت حساب و نشست‌ها'],['i-market','داده بازار','منابع و وضعیت اتصال'],['i-wallet','دارایی','کیف پول و تبدیل'],['i-trade','معامله','سفارش‌های نمایشی']];return `<div class="view-head"><div><h1>مرکز TeeXaa</h1><p>بخش‌های اختصاصی، بدون شلوغی</p></div></div><div class="page-grid">${items.map(x=>`<button class="feature" onclick="toast('${x[1]} باز شد')"><span class="fi">${icon(x[0])}</span><h3>${x[1]}</h3><p>${x[2]}</p></button>`).join('')}</div>`}
function profile(){return `<div class="view-head"><div><h1>حساب کاربری</h1><p>پروفایل و کنترل‌های شخصی</p></div></div><div class="profile-grid"><div class="profile-card"><div class="big-avatar">T</div><h2>TeeXaa User</h2><p>حساب نمایشی · Standard</p><button class="tool-btn" style="background:#fff;margin-top:8px" onclick="toast('ویرایش پروفایل')">ویرایش پروفایل</button></div><div class="setting-list">${[['امنیت حساب','کنترل نشست‌ها و ورود دومرحله‌ای'],['اعلان‌های بازار','اطلاع از تغییرات قیمت و رویدادها'],['حالت ترمینال','نمای حرفه‌ای داده‌های بازار'],['ورود سریع','آماده برای اتصال به احراز هویت']].map((x,i)=>`<div class="setting"><div><b>${x[0]}</b><small>${x[1]}</small></div><div class="switch ${i<3?'on':''}" onclick="this.classList.toggle('on')"></div></div>`).join('')}</div></div>`}
function notifications(){return `<div class="view-head"><div><h1>اعلان‌ها</h1><p>رویدادهای TeeXaa</p></div></div><div class="setting-list">${[['بازار','داده‌های بازار بروزرسانی شدند.'],['سیستم','اتصال به منابع عمومی برقرار است.'],['حساب','این نسخه هنوز حساب واقعی ندارد.']].map(x=>`<div class="setting"><div><b>${x[0]}</b><small>${x[1]}</small></div><span class="card-sub">همین حالا</span></div>`).join('')}</div>`}
function security(){return `<div class="view-head"><div><h1>امنیت</h1><p>مرکز کنترل دسترسی TeeXaa</p></div></div><div class="page-grid"><button class="feature" onclick="toast('2FA در نسخه متصل فعال می‌شود')"><span class="fi">${icon('i-lock')}</span><h3>تأیید دومرحله‌ای</h3><p>برای نسخه واقعی آماده اتصال است.</p></button><button class="feature" onclick="toast('مدیریت نشست‌ها')"><span class="fi">${icon('i-grid')}</span><h3>نشست‌ها</h3><p>دستگاه‌های متصل را مدیریت کنید.</p></button></div>`}
function go(p){state.page=p;render();scrollTo({top:0,behavior:'smooth'})}window.go=go;
async function refreshRates(){toast('در حال دریافت نرخ‌ها...');try{const [fx,gold,btc]=await Promise.all([fetch('https://open.er-api.com/v6/latest/USD').then(r=>r.json()),fetch('https://api.gold-api.com/price/XAU').then(r=>r.json()),fetch('https://api.gold-api.com/price/BTC').then(r=>r.json())]);state.rates.usd=fx?.rates?.IRR||null;state.rates.eur=fx?.rates?.EUR?state.rates.usd/fx.rates.EUR:null;state.rates.aed=fx?.rates?.AED?state.rates.usd/fx.rates.AED:null;state.rates.try=fx?.rates?.TRY?state.rates.usd/fx.rates.TRY:null;state.rates.xau=gold?.price??gold?.value??gold?.result??null;state.rates.btc=btc?.price??btc?.value??btc?.result??null;state.updated=new Intl.DateTimeFormat('fa-IR',{hour:'2-digit',minute:'2-digit'}).format(new Date());render();toast('نرخ‌ها بروزرسانی شدند')}catch(e){toast('اتصال نرخ‌ها در دسترس نیست');render()}}
const views={home,markets,trade,wallet,more,profile,notifications,security};
function render(){if(!views[state.page])state.page='home';$('#view').innerHTML=views[state.page]();$('#railNav').innerHTML=railHtml();$('#bottomNav').innerHTML=navHtml();$$('[data-page]').forEach(b=>{b.onclick=()=>go(b.dataset.page)});}
window.addEventListener('load',()=>{let p=0;const t=setInterval(()=>{p=Math.min(100,p+4);$('#bootPct').textContent=String(p).padStart(2,'0')+'%';if(p>=100){clearInterval(t);setTimeout(()=>{$('#splash').style.opacity='0';$('#splash').style.transition='opacity .55s ease';setTimeout(()=>{$('#splash').remove();$('#app').classList.remove('hidden')},550)},700)}},55);render();refreshRates()});
